<?php

namespace Lotzwoo\Translations;

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Composes a textual .po file from scanned entries + a translations map.
 */
class PO_File
{
    /**
     * @param array<string, array{msgid:string, msgid_plural:?string, msgctxt:?string, refs:string[]}> $entries
     * @param array<string, string> $translations  key => msgstr (key matches the entry key, optional "__plural" suffix for the plural form)
     */
    public function compose(array $entries, array $translations, string $locale): string
    {
        $out = $this->header($locale);
        foreach ($entries as $key => $entry) {
            $out .= "\n";
            foreach ($entry['refs'] as $ref) {
                $out .= '#: ' . $ref . "\n";
            }
            if ($entry['msgctxt'] !== null) {
                $out .= 'msgctxt ' . $this->quote($entry['msgctxt']) . "\n";
            }
            $out .= 'msgid ' . $this->quote($entry['msgid']) . "\n";

            if ($entry['msgid_plural'] !== null) {
                $out .= 'msgid_plural ' . $this->quote($entry['msgid_plural']) . "\n";
                $msgstr_0 = (string) ($translations[$key] ?? '');
                $msgstr_1 = (string) ($translations[$key . '__plural'] ?? '');
                $out .= 'msgstr[0] ' . $this->quote($msgstr_0) . "\n";
                $out .= 'msgstr[1] ' . $this->quote($msgstr_1) . "\n";
            } else {
                $msgstr = (string) ($translations[$key] ?? '');
                $out .= 'msgstr ' . $this->quote($msgstr) . "\n";
            }
        }
        return $out;
    }

    private function header(string $locale): string
    {
        $when = gmdate('Y-m-d H:iO');
        return "# Translation for the LotzApp for WooCommerce plugin.\n"
            . "# Locale: {$locale}\n"
            . "# Generated by LotzApp Translations.\n"
            . "msgid \"\"\n"
            . "msgstr \"\"\n"
            . '"Project-Id-Version: LotzApp for WooCommerce\\n"' . "\n"
            . '"Report-Msgid-Bugs-To: \\n"' . "\n"
            . '"PO-Revision-Date: ' . $when . '\\n"' . "\n"
            . '"Language: ' . $locale . '\\n"' . "\n"
            . '"MIME-Version: 1.0\\n"' . "\n"
            . '"Content-Type: text/plain; charset=UTF-8\\n"' . "\n"
            . '"Content-Transfer-Encoding: 8bit\\n"' . "\n"
            . '"Plural-Forms: nplurals=2; plural=n != 1;\\n"' . "\n"
            . '"X-Generator: LotzApp\\n"' . "\n";
    }

    private function quote(string $s): string
    {
        // Order-safe escape via strtr (longest match, no chained re-scan).
        $escaped = strtr($s, [
            '\\' => '\\\\',
            '"'  => '\\"',
            "\n" => '\\n',
            "\r" => '\\r',
            "\t" => '\\t',
        ]);
        return '"' . $escaped . '"';
    }
}
