<?php
/**
 * Plugin Name:       LotzApp for WooCommerce
 * Description:       Erweitert WooCommerce-Shops um Ca.-Preislogik, Admin-Tools zur Datenpflege, automatisierte Menüaktualisierung und mehr.
 * Version:           0.1.15
 * Author:            somesunnymind.com
 * Requires at least: 5.8
 * Requires PHP:      8.1
 * Text Domain:       lotzapp-for-woocommerce
 * Domain Path:       /languages
 */

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly.
}

// Minimum environment checks.
define('LOTZWOO_MIN_PHP', '7.4');
if (version_compare(PHP_VERSION, LOTZWOO_MIN_PHP, '<')) {
    add_action('admin_notices', static function () {
        echo '<div class="notice notice-error"><p>' . esc_html__('LotzApp for WooCommerce requires PHP 7.4 or higher.', 'lotzapp-for-woocommerce') . '</p></div>';
    });
    return;
}

// Define plugin constants.
if (!defined('LOTZWOO_PLUGIN_FILE')) {
    define('LOTZWOO_PLUGIN_FILE', __FILE__);
}
if (!defined('LOTZWOO_PLUGIN_DIR')) {
    define('LOTZWOO_PLUGIN_DIR', plugin_dir_path(__FILE__));
}
if (!defined('LOTZWOO_PLUGIN_URL')) {
    define('LOTZWOO_PLUGIN_URL', plugin_dir_url(__FILE__));
}
if (!defined('LOTZWOO_GITHUB_OWNER')) {
    define('LOTZWOO_GITHUB_OWNER', 'somesunnymind');
}
if (!defined('LOTZWOO_GITHUB_REPOSITORY')) {
    define('LOTZWOO_GITHUB_REPOSITORY', 'lotzapp-for-woocommerce');
}
if (!defined('LOTZWOO_GITHUB_BRANCH')) {
    define('LOTZWOO_GITHUB_BRANCH', 'main');
}

// Declare HPOS (Custom Order Tables) compatibility.
add_action('before_woocommerce_init', static function () {
    if (class_exists(\Automattic\WooCommerce\Utilities\FeaturesUtil::class)) {
        \Automattic\WooCommerce\Utilities\FeaturesUtil::declare_compatibility('custom_order_tables', __FILE__, true);
    }
});

// Load translations. WP 6.7+ requires this on `init` (or later), not earlier.
if (!function_exists('lotzwoo_load_main_textdomain')) {
    function lotzwoo_load_main_textdomain(?string $locale = null): void
    {
        $domain = 'lotzapp-for-woocommerce';
        $locale = $locale !== null && $locale !== '' ? $locale : get_locale();

        load_plugin_textdomain(
            $domain,
            false,
            dirname(plugin_basename(LOTZWOO_PLUGIN_FILE)) . '/languages'
        );

        $candidates = [
            trailingslashit(WP_LANG_DIR) . 'plugins/' . $domain . '-' . $locale . '.mo',
            trailingslashit(LOTZWOO_PLUGIN_DIR) . 'languages/' . $domain . '-' . $locale . '.mo',
        ];

        foreach ($candidates as $mo) {
            if (!is_string($mo) || !file_exists($mo)) {
                continue;
            }

            unload_textdomain($domain);
            load_textdomain($domain, $mo);
            return;
        }
    }
}
add_action('init', static function () {
    lotzwoo_load_main_textdomain();
});

/**
 * Per-email content translations.
 *
 * Each email's user-entered replace-field text (intro / body / reset_*) is
 * looked up at render-time via __() against a per-email text domain
 * "lotzapp-email-<email_id>". The matching .mo file lives at
 * wp-content/languages/plugins/lotzapp-email-<email_id>-<locale>.mo and is
 * generated by the LotzApp Übersetzungen page (or edited manually in Loco).
 * Registering them here also lets Loco's listener associate the domains with
 * this plugin bundle, so Loco shows them in the bundle view.
 */
if (!function_exists('lotzwoo_load_email_textdomains')) {
    /**
     * Load per-email translation .mo files for a specific locale.
     * Used at runtime (front-end email render) so the correct locale's
     * translations are active when __() is called.
     */
    function lotzwoo_load_email_textdomains(?string $locale = null): void
    {
        $locale = $locale !== null && $locale !== '' ? $locale : determine_locale();
        $dir    = trailingslashit(WP_LANG_DIR) . 'plugins/';
        if (!is_dir($dir)) {
            return;
        }
        $files = glob($dir . 'lotzapp-email-*-' . $locale . '.mo');
        if (!is_array($files)) {
            return;
        }
        $suffix_len = strlen('-' . $locale . '.mo');
        foreach ($files as $mo) {
            $basename = basename($mo);
            $domain   = substr($basename, 0, -$suffix_len);
            if ($domain === '' || strpos($domain, 'lotzapp-email-') !== 0) {
                continue;
            }
            unload_textdomain($domain);
            load_textdomain($domain, $mo);
        }
    }
}
if (!function_exists('lotzwoo_register_email_textdomains_for_loco')) {
    /**
     * Register every per-email text domain we have ANY .mo file for, so
     * Loco's listener associates them with this plugin bundle and lists
     * each per-email domain in Loco's bundle view. Runs in admin only,
     * where wrong-locale loading is harmless (no emails render there).
     */
    function lotzwoo_register_email_textdomains_for_loco(): void
    {
        $dir = trailingslashit(WP_LANG_DIR) . 'plugins/';
        if (!is_dir($dir)) {
            return;
        }
        $files = glob($dir . 'lotzapp-email-*-*.mo');
        if (!is_array($files)) {
            return;
        }
        $seen = [];
        foreach ($files as $mo) {
            $basename = basename($mo);
            if (!preg_match('/^(lotzapp-email-.+)-([a-z]{2,3}(?:_[A-Za-z0-9]{2,8})?)\.mo$/', $basename, $m)) {
                continue;
            }
            $domain = $m[1];
            if (isset($seen[$domain])) {
                continue;
            }
            $seen[$domain] = true;
            if (function_exists('is_textdomain_loaded') && is_textdomain_loaded($domain)) {
                continue; // already loaded by the runtime hook for current locale
            }
            load_textdomain($domain, $mo);
        }
    }
}
add_action('init', static function () {
    lotzwoo_load_email_textdomains();
}, 5);
add_action('change_locale', static function ($new_locale) {
    lotzwoo_load_main_textdomain((string) $new_locale);
    lotzwoo_load_email_textdomains((string) $new_locale);
});
add_action('admin_init', 'lotzwoo_register_email_textdomains_for_loco');

/**
 * Register each per-email text domain as its own project on this plugin's
 * Loco bundle. Loco's auto-config only picks up the plugin's TextDomain header
 * (lotzapp-for-woocommerce); without this, our extra domains aren't part of
 * the bundle and Loco's file editor shows "Sync is disabled because this file
 * doesn't relate to a known set of translations." Adding them as projects
 * also makes them appear in the bundle overview alongside the main UI domain.
 */
add_action('loco_bundle_configured', static function ($bundle) {
    if (!class_exists('\\Loco_package_Plugin')) {
        return;
    }
    if (!($bundle instanceof \Loco_package_Plugin)) {
        return;
    }
    if ($bundle->getHandle() !== plugin_basename(LOTZWOO_PLUGIN_FILE)) {
        return;
    }

    $dir = trailingslashit(WP_LANG_DIR) . 'plugins/';
    if (!is_dir($dir)) {
        return;
    }
    $files = glob($dir . 'lotzapp-email-*-*.mo');
    if (!is_array($files)) {
        return;
    }

    $seen = [];
    foreach ($files as $mo) {
        $basename = basename($mo);
        if (!preg_match('/^(lotzapp-email-.+)-([a-z]{2,3}(?:_[A-Za-z0-9]{2,8})?)\.mo$/', $basename, $m)) {
            continue;
        }
        $domain = $m[1];
        if (isset($seen[$domain])) {
            continue;
        }
        $seen[$domain] = true;
        if ($bundle->getProject($domain)) {
            continue;
        }
        $project = new \Loco_package_Project(
            $bundle,
            new \Loco_package_TextDomain($domain),
            $domain
        );
        $bundle->addProject($project);
    }
}, 20);

// Lightweight PSR-4-like autoloader for the Lotzwoo namespace.
spl_autoload_register(static function ($class) {
    if (strpos($class, 'Lotzwoo\\') !== 0) {
        return;
    }

    $relative = substr($class, strlen('Lotzwoo\\'));
    $base_dir = LOTZWOO_PLUGIN_DIR . 'includes' . DIRECTORY_SEPARATOR;

    $candidates = [];

    $ns_path = str_replace('\\', DIRECTORY_SEPARATOR, $relative) . '.php';
    $candidates[] = $base_dir . $ns_path;
    $candidates[] = $base_dir . strtolower($ns_path);
    $ns_dir = dirname($ns_path);
    $ns_file = basename($ns_path);
    if ($ns_dir !== '.' && $ns_file !== '') {
        $candidates[] = $base_dir . $ns_dir . DIRECTORY_SEPARATOR . strtolower($ns_file);
    }

    $parts = explode('\\', $relative);
    $parts = array_map(static function ($part) {
        $part = preg_replace('/([a-z0-9])([A-Z])/', '$1_$2', $part);
        $part = preg_replace('/([A-Z])([A-Z][a-z])/', '$1_$2', $part);
        return strtolower($part);
    }, $parts);
    $candidates[] = $base_dir . implode(DIRECTORY_SEPARATOR, $parts) . '.php';

    foreach ($candidates as $file) {
        if ($file && file_exists($file)) {
            require_once $file;
            return;
        }
    }
});

$lotzwoo_updater_config = [
    'owner'       => LOTZWOO_GITHUB_OWNER,
    'repository'  => LOTZWOO_GITHUB_REPOSITORY,
    'branch'      => LOTZWOO_GITHUB_BRANCH,
    'plugin_file' => LOTZWOO_PLUGIN_FILE,
    'slug'        => 'lotzapp-for-woocommerce',
    'token'       => defined('LOTZWOO_GITHUB_TOKEN') ? LOTZWOO_GITHUB_TOKEN : null,
];

$lotzwoo_updater_config = apply_filters('lotzwoo/github_updater_config', $lotzwoo_updater_config);

Lotzwoo\Updates\GitHub_Updater::boot($lotzwoo_updater_config);

register_activation_hook(__FILE__, static function () {
    Lotzwoo\Plugin::activate();
});

register_deactivation_hook(__FILE__, static function () {
    Lotzwoo\Plugin::deactivate();
});

// Ensure WooCommerce present before booting the plugin.
add_action('plugins_loaded', static function () {
    if (!class_exists('WooCommerce')) {
        add_action('admin_notices', static function () {
            echo '<div class="notice notice-error"><p>' . esc_html__('LotzApp for WooCommerce requires WooCommerce to be active.', 'lotzapp-for-woocommerce') . '</p></div>';
        });
        return;
    }

    // Boot the plugin.
    Lotzwoo\Plugin::instance();
});
